#!/bin/bash

# Simple deployment script for IOTA Playground on remote server
# Run this after transferring files to the server

echo "==================================="
echo "IOTA Playground Simple Deployment"
echo "==================================="

# Simple commands to run on your remote server:
echo ""
echo "Run these commands on your remote server:"
echo ""
echo "1. Stop Wizard temporarily to free port 80:"
echo "   cd /root/wizard/backend"
echo "   docker-compose stop"
echo ""
echo "2. Deploy IOTA Playground:"
echo "   cd /root/iota-playground/backend"
echo "   docker-compose build --no-cache"
echo "   docker-compose up -d"
echo ""
echo "3. Get SSL certificate:"
echo "   docker exec iota-playground-backend certbot certonly --standalone -d api.iotaplay.app --email tolga+iotaplay@yk-labs.com --agree-tos --no-eff-email"
echo ""
echo "4. Restart Wizard:"
echo "   cd /root/wizard/backend"
echo "   docker-compose start"
echo ""
echo "5. Test endpoints:"
echo "   curl https://api.iotaplay.app:8444/api/health"
echo "   curl https://api.thewizard.app:8443/health"
echo ""
echo "==================================="
echo "Alternative: Run without SSL first"
echo "==================================="
echo ""
echo "If SSL is problematic, modify entrypoint.sh to skip SSL:"
echo "1. Comment out certbot lines in entrypoint.sh"
echo "2. Use HTTP only for testing"
echo "3. Access via: http://YOUR_SERVER_IP:8081/api/health"