version: '3.8'

services:
  # Shared nginx proxy for handling port 80 and Let's Encrypt challenges
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    name: proxy-network