[package]
name = "user_project"
edition = "2024.beta"

[dependencies]
# IOTA dependencies are automatically included by the CLI

[addresses]
# Common addresses for user modules
user_module = "0x0"
hello_world = "0x0"
counter = "0x0"
token = "0x0"
nft = "0x0"
defi = "0x0"
game = "0x0"