[package]
name = "user_project"
edition = "2024.beta"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/testnet" }

[addresses]
user_project = "0x0"
hello_world = "0x0"
counter = "0x0"
user_module = "0x0"
greetings = "0x0"